version: "3.9"
services:
  fastapi_app:
    build: './app'
    ports:
      - "80:80"
    depends_on:
      - rabbit

  rabbit:
    hostname: rabbit
    image: "rabbitmq:3-management"
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mypass
    ports:
      - "15672:15672"
      - "5672:5672"

  worker:
    build: './celery_task_app'
    user: nobody
    depends_on:
      - rabbit
      - fastapi_app
    command: ["celery", "-A", "celery_task_app.worker.app", "worker", "--loglevel=info"]
